prizelists:
  - rocks:
# With 70% probability, the player gets 10 diorite, 10 andesite, and 20 granite.
# With 20% probability, the player gets a stack of bricks
# 9% for 5 obsidian
# 1% for 1 bedrock
# The numbers don't have to add up to 100, they're just relative frequencies of occurence
      - stones: "70 1:3(10) 1:5(10) 1:1(20)"
      - bricks: "20 45(64)"
      - obsidian: "9 49(5)"
      - bedrock: "1 7(1)"
  - gems:
# 1 in 5 cases gives the player 5 emeralds, 3 in 5 cases is one diamond, and 1 in 5 is $1000:
      - emerald: "1 388(5)"
      - diamond: "3 264(1)"
      - money: "1 0(1000)"
  - money:
      - standard: "90 0(100)"
      - lucky: "9 AIR(1000)"
      - jackpot: "1 AIR(10000)"
gamemodes:
  - default:
      delay: 120                 # seconds between questions - 2 minutes
      answertime: 20             # seconds to answer, if noone answers within this time the question expires
      answercount: 1             # Only the first player who answers gets a score point
      filepattern: default*.txt  # Cycle between all files that are named "default*"
      prefix: "&5"               # all messages in dark purple
      nextgamemode: default      # After finishing a round, restart the same game mode
      threshold: 1               # Give a prize to the "winning" player after every question
      prizelist: rocks
      numwinners: 1              # Only the "best" player wins a prize.
      questionmessage: "&2Trivia Time! &6Use /ans to answer: &5%question% &7(%answer%)"
      itemmessage: "The correct answer was %answer%, found by %players%."
      timeoutmessage: "Noone found the answer, which was %answer%."
      rewardmessage: "%winners% get%winners.s% a box of %prizelist% each."
  - event:
      delay: 20
      answertime: 10             # people are expected to respond much faster here
      answercount: 3             # The 3 first players to answer get a score point each
      filepattern: event*.txt    # use one of a special set of questions/answers
      prefix: "&b"               # all messages in Aqua
      nextgamemode: default      # Go to default mode after finishing a q/a file
      threshold: all             # Give a prize to the player(s) who has/have the highest score after all questions
      prizelist: gems
      numwinners: 3              # The 3 best players get a prize each
      # numwinners: 10%            # Alternative: The best 10% of players get a prize each - TODO not implemented yet!
      questionmessage: "Knowledge Event! %question% &7(%answer%)"
      startmessage: "Starting knowledge event."
      endmessage: "Ending knowledge event."
      itemmessage: "%players% found the correct answer %answer% first and get%players.s% a point"
      timeoutmessage: "How sad %answer% wasn't found by anyone."
      rewardmessage: "&1Best players:\n%scoreboard%Gem prizes go to %winners%."
  - easter:
      # copy most of event's stuff ...
      copyfrom: event
      # You can omit this section and start the easter event with "/knowledge mode event easterquestions.txt".
      filepattern: easterquestions.txt
  - scrambleall:
      copyfrom: event
      scramble: all             # "none" scrambles none, "marked" scrambles {..},
                                # "all" means 1 line per question which is answer AND question(after scrambling)
      filepattern: scrambleall*.txt
  - scrambleline:
      copyfrom: event
      scramble: line
      filepattern: scrambleline*.txt
# This asks a question from the test file every 15 seconds, and gives the answer 
# after another 30 seconds. This time should be enough to answer and do a 
# /pok stats before and after the answer is shown.
# Test mode 1 runs all questions, allows up to 3 players to answer a question,
# and awards the prize after all questions have been answered. The best 2
# players win a prize each.
  - test1:
      delay: 15
      answertime: 10
      answercount: 3
      filepattern: test.txt
      prefix: "&e"
      nextgamemode: default
      threshold: all
      prizelist: gems
      numwinners: 2
      startmessage: "starting event %name% - first %answercount% answer%answercount.s% per question get a score point, prize to %numwinners% player%numwinners.s% after %threshold% questions"
      endmessage:   "ending event %name%"
      itemmessage:  "&2answer &d%answer% &2found by %players%"
      timeoutmessage: "&canswer &d%answer% &cnot found by anyone"
      rewardmessage: "rewarding %winners% with a box of %prizelist%"
      norewardmessage: "No prizes this time"
  - test2:
# In this test, only the fastest answer counts, and the best player(s) get a
# prize after 3 questions. As there are 8 questions in the question file,
# a prize should be given after 3, 6, and 8 questions.
      copyfrom: test1
      answercount: 1
      threshold: 3
      randomize: no
  - test3:
# This should get disabled, and /pok mode test3 should result in an error message.
      copyfrom: test1
      prizelist: undefined
  - test4:
      copyfrom: test1
      answercount: 1
      numWinners: 1
      threshold: 1
      prizelist: money