gamemodes:
  - default:
      delay: 1200                # seconds between questions - 20 minutes
      answertime: 60             # seconds to answer, if noone answers within this time the question expires
      answercount: 1             # Only the first player who answers gets a score point
      filepattern: default*.txt  # Cycle between all files that are named "default*"
      prefix: &5                 # Use dark purple for questions
      nextgamemode: default      # After finishing a round, restart the same game mode
      threshold: 1               # Give a prize to the "winning" player after every question
      prizelist: rocks
      numwinners: 1              # Only the "best" player wins a prize.
      itemmessage: "The correct answer was %answer%. %playerlist% gets a box of rocks."
      expiremessage: "Noone found the answer, which was %answer%."
  - event:
      delay: 200
      answertime: 10             # people are expected to respond much faster here
      answercount: 3             # The 3 first players to answer get a score point each
      filepattern: event*.txt    # use one of a special set of questions/answers
      prefix: &b                 # ask questions in Aqua
      nextgamemode: default      # Go to default mode after finishing a q/a file
      threshold: all             # Give a prize to the player(s) who has/have the highest score after all questions
      prizelist: gems
      numwinners: 3              # The 3 best players get a prize each
      numwinners: 10%            # Alternative: The best 10% of players get a prize each
      startmessage: "Starting knowledge event."
      endmessage: "Ending knowledge event. Gem prizes go to %playerlist%"
      itemmessage: "%playerlist% found the correct answer %answer% first and get a point each"
      expiremessage: "How sad %answer% wasn't found by anyone."
  - easter:
      # copy most of event's stuff ...
      # You can omit this section and start the easter event with "/knowledge mode event easterquestions.txt".
      filepattern: easterquestions.txt

prizelists:
  - rocks:
# With 70% probability, the player gets 10 diorite, 10 andesite, and 20 granite.
# With 20% probability, the player gets a stack of bricks
# 9% for 5 obsidian
# 1% for 1 bedrock
# The numbers don't have to add up to 100, they're just relative frequencies of occurence
# The name tags are just for readability and not used by the system
    - rocks: "70 1:3(10) 1:5(10) 1:1(20)"
    - bricks: "20 45(64)"
    - obsidian: "9 49(5)"
    - bedrock: "1 7(1)"
  - gems:
# 1 in 5 cases gives the player 5 emeralds, 3 in 5 cases is one diamond, and 1 in 5 is $1000:
    - emerald: "1 388(5)"
    - diamond: "3 264(1)"
    - money: "1 0(1000)"