## YAML Template.
name: PursuitOfKnowledge
main: de.guntram.bukkit.pursuitofknowledge.PoK
version: 0.12
commands:
    answer:
        description: Answer the last question.
        usage: /answer <text>
        permission: pok.answer
        permission-message: No right to answer
    pok:
        description: Manage the PoK plugin
        usage: /pok stats|answer|mode <modename> (<filename>)|reload
        permission: pok.admin
softdepend: [Vault]